### ISSUE TITLE
Hacktoberfest Label

### ISSUE THREAD

**Issue by akanshbende** [dev-AshishRanjan/Hello-World-starter-project#15]
ADD Hacktober fest label

**Comment by dev-AshishRanjan** [comment]
@akanshbende ,
This is excluded form hacktoberfest 

You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.

Happy Contributing season!
Keep up the good work!
